[package]
name = "raft"
version = "0.5.0"
authors = ["The TiKV Project Developers"]
license = "Apache-2.0"
keywords = ["raft", "distributed-systems", "ha"]
repository = "https://github.com/pingcap/raft-rs"
readme = "README.md"
homepage = "https://github.com/pingcap/raft-rs"
documentation = "https://docs.rs/raft"
description = "The rust language implementation of Raft algorithm."
categories = ["algorithms", "database-implementations"]
edition = "2018"

[features]
default = []
failpoint = ["fail"]

[dependencies]
slog = "2.2"
protobuf = "~2.0-2.2"
quick-error = "1.2.2"
rand = "0.5.4"
hashbrown = "0.1"
fail = { version = "0.2", optional = true }
getset = "0.0.6"
slog-async = "2.3.0"
slog-stdlog = "3.0.2"
slog-term = "2.4.0"
slog-envlogger = "2.1.0"

[dev-dependencies]
criterion = ">0.2.4"
lazy_static = "1.0"
regex = "1.1"

[[bench]]
name = "benches"
harness = false

[badges]
travis-ci = { repository = "pingcap/raft-rs" }

[[example]]
name = "single_mem_node"
path = "examples/single_mem_node/main.rs"

[[example]]
name = "five_mem_node"
path = "examples/five_mem_node/main.rs"
